Http/routes.php
<?php
Route::group(['middleware' => ['web']], function () {
    Route::group(array("prefix" => "admin", "as"=>"admin."), function () {
        Route::group(['middleware' => 'auth:dcms'], function () {

                //EMPLOYEES
            Route::group(array("prefix" => "employees" ,"as"=>"employees."), function () {
                Route::get('{id}/copy', array('as'=>'copy', 'uses' => 'EmployeeController@copy'));
                Route::get('employeerelation/{employee_id?}', array('as'=>'employeerelation', 'uses' => 'EmployeeController@getEmployeeRelation'));

                //CATEGORIES
                Route::group(array("prefix" => "categories", "as"=>"categories."), function () {
                    Route::get('{id}/copy', array('as'=>'{id}.copy', 'uses' => 'CategoryController@copy'));
                    Route::any('api/table', array('as'=>'api.table', 'uses' => 'CategoryController@getDatatable'));
                });
                Route::resource('categories', 'CategoryController');

                //API
                Route::group(array("prefix" => "api", "as"=>"api."), function () {
                    Route::any('table', array('as'=>'table', 'uses' => 'EmployeeController@getDatatable'));
                });
            });
            Route::resource('employees', 'EmployeeController');
        });
    });
});

Http/Controllers/EmployeeController.php
<?php

namespace Dcms\Employees\Http\Controllers;

use Dcms\Employees\Models\Employee;
use Dcms\Employees\Models\EmployeeToEmployee;
use Dcms\Employees\Models\Detail;
use Dcms\Employees\Models\Category;

//use Dcweb\Dcms\Models\Pages\Page;
//use Dcweb\Dcms\Controllers\Pages\PageController;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use View;
use Input;
use Session;
use Validator;
use Redirect;
use DB;
use DataTables;
use Auth;
use Form;
use DateTime;

class EmployeeController extends Controller
{
    public $employee_language_Columnnames = [];
    public $employee_Columnnames = [];

    public $employeelanguageFormTemplate = "";
    public $employeeFormTemplate = "";

    public $extendgeneralTemplate = "";

    public function __construct()
    {
        $this->middleware('permission:employees-browse')->only('index');
        $this->middleware('permission:employees-add')->only(['create', 'store']);
        $this->middleware('permission:employees-edit')->only(['edit', 'update']);
        $this->middleware('permission:employees-delete')->only('destroy');

        //note startdate and enddate are defaults, since these are always there, and have a specific value (not simple text, or bool)
        $this->employee_Columnnames = [
            'thumbnail'     => 'thumbnail',
            'online'        => 'online',
            'newemployee'    => 'newemployee',
        ];

        $this->employee_language_Columnnames = [
            'employee_category_id' => 'category_id',
            'title'               => 'title',
            'description'         => 'description',
            'sort_id'         => 'sort_id',
            'body'                => 'body',
            'slug'                => 'title',
            'path'                => 'title',
            'url'                 => 'url',
        ];

        $this->employeelanguageFormTemplate = null;
        $this->employeeFormTemplate = null;
    }

    public static function getEmployeesDetailByLanguage($language_id = null)
    {
        return Detail::where("language_id", "=", $language_id)->lists("title", "id");
    }

    public static function getDropdownEmployeesByLanguage($language_id = null)
    {
        $dropdownvalues = EmployeeController::getEmployeesDetailByLanguage($language_id);

        return Form::select("employee[" . $language_id . "][]", $dropdownvalues, [3, 4, 5, 6], ["id" => "employees-" . $language_id, "multiple" => "multiple"]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        // load the view
        return View::make('dcms::employees/index');
    }


    public function getDatatable()
    {
        return DataTables::queryBuilder(
            DB::connection('project')
                ->table('employees')
                ->select(
                    'employees.id',
                    'employees_language.title',
                    'employees_language.id as employee_language_id',
                    'employees_categories_language.title as category',
                    (DB::connection("project")->raw('Concat("<img src=\'/packages/dcms/core/images/flag-",lcase(country),".png\' >") as country'))
                )
                ->join('employees_language', 'employees.id', '=', 'employees_language.employee_id')
                ->leftJoin('employees_categories_language', 'employees_categories_language.id', '=', 'employees_language.employee_category_id')
                ->leftJoin('languages', 'employees_language.language_id', '=', 'languages.id')
        )
            ->addColumn('edit', function ($model) {
                $edit = '<form method="POST" action="/admin/employees/' . $model->employee_language_id . '" accept-charset="UTF-8" class="pull-right">
								<input name="_token" type="hidden" value="' . csrf_token() . '">
								<input name="_method" type="hidden" value="DELETE">';
                if (Auth::user()->can('employees-edit')) {
                    $edit .= '<a class="btn btn-xs btn-default" href="/admin/employees/' . $model->id . '/edit"><i class="far fa-pencil"></i></a>';
                }
                if (Auth::user()->can('employees-add')) {
                    $edit .= '<a class="btn btn-xs btn-default" href="/admin/employees/' . $model->employee_language_id . '/copy"><i class="far fa-copy"></i></a>';
                }
                if (Auth::user()->can('employees-delete')) {
                    $edit .= '<button class="btn btn-xs btn-default" type="submit" value="Delete this employee" onclick="if(!confirm(\'Are you sure to delete this item ? \')){return false;};"><i class="far fa-trash-alt"></i></button>';
                }
                $edit .= '</form>';

                return $edit;
            })
            ->rawColumns(['country', 'edit'])
            ->make(true);
    }

    public function getInformation($id = null)
    {
        if (is_null($id)) {
            return DB::connection("project")->table("languages")->select((DB::connection("project")->raw("'' as title, NULL as sort_id, (select max(sort_id) from employees_language where language_id = languages.id) as maxsort, '' as description , '' as body, '' as url, '' as employee_category_id, '' as id")), "id as language_id", "language", "country", "language_name")->get();
        } else {
            return DB::connection("project")->select('
													SELECT language_id, languages.language, languages.country, languages.language_name, employee_category_id, employees_language.id, employee_id, title, sort_id, (select max(sort_id) from employees_language as X  where X.language_id = employees_language.language_id) as maxsort,  description, body, url, date_format(startdate,\'%d-%m-%Y\') as startdate , date_format(enddate,\'%d-%m-%Y\')  as enddate
													FROM employees_language
													LEFT JOIN languages on languages.id = employees_language.language_id
													LEFT JOIN employees on employees.id = employees_language.employee_id
													WHERE  languages.id is not null AND  employee_id = ?
													UNION
													SELECT languages.id , language, country, language_name, \'\' , \'\' ,  \'\' , \'\' , NULL as sort_id, (select max(sort_id) from employees_language where language_id = languages.id) as maxsort, \'\' , \'\'  , \'\' , \'\' , \'\'
													FROM languages
													WHERE id NOT IN (SELECT language_id FROM employees_language WHERE employee_id = ?) ORDER BY 1
													', [$id, $id]);
        }
    }

    public function getExtendedModel()
    {
        //do nothing let the extend class hook into this
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $languages = $this->getInformation();

        // load the create form (app/views/employees/create.blade.php)
        return View::make('dcms::employees/form')
            ->with('languages', $languages)
            ->with('categoryOptionValues', Category::OptionValueTreeArray(false))
            ->with('pageOptionValuesSelected', [])
            ->with('sortOptionValues', $this->getSortOptions($languages, 1))
            ->with('employeelanguageFormTemplate', $this->employeelanguageFormTemplate)
            ->with('employeeFormTemplate', $this->employeeFormTemplate)
            ->with('extendgeneralTemplate', ['template' => $this->extendgeneralTemplate, 'model' => $this->getExtendedModel()]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $employee = Employee::find($id);
        $cat = $employee->category;

        // show the view and pass the nerd to it
        return View::make('dcms::employees/show')
            ->with('employee', $employee)
            ->with("category", $cat->title);
    }

    public function getSortOptions($model, $setExtra = 0)
    {
        foreach ($model as $M) {
            $increment = 0;
            if ($setExtra > 0) {
                $increment = $setExtra;
            }
            if (intval($M->id) <= 0 && !is_null($M->maxsort)) {
                $increment = 1;
            }

            $maxSortID = $M->maxsort;
            if (is_null($maxSortID)) {
                $maxSortID = 1;
            }

            for ($i = 1; $i <= ($maxSortID + $increment); $i++) {
                $SortOptions[$M->language_id][$i] = $i;
            }
        }

        return $SortOptions;
    }

    public function getSelectedPages($employeeid = null)
    {
        return DB::connection("project")->select('  SELECT employee_detail_id, page_id
													FROM employees_language_to_pages
													WHERE employee_detail_id IN (SELECT id FROM employees_language WHERE employee_id = ?)', [$employeeid]);
    }

    public function setPageOptionValues($objselected_pages)
    {
        $pageOptionValuesSelected = [];
        if (count($objselected_pages) > 0) {
            foreach ($objselected_pages as $obj) {
                $pageOptionValuesSelected[$obj->page_id] = $obj->page_id;
            }
        }

        return $pageOptionValuesSelected;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $employee = Employee::find($id);
        $employee->startdate = (is_null($employee->startdate) ? null : DateTime::createFromFormat('Y-m-d', $employee->startdate)->format('m/d/Y'));
        $employee->enddate = (is_null($employee->enddate) ? null : DateTime::createFromFormat('Y-m-d', $employee->enddate)->format('m/d/Y'));

        $objlanguages = $this->getInformation($id);
        $objselected_pages = $this->getSelectedPages($id);

        return View::make('dcms::employees/form')
            ->with('employee', $employee)
            ->with('languages', $objlanguages)

resources/views/employees/index.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
        <h1>Employees</h1>
        <ol class="breadcrumb">
            <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
            <li class="active"><i class="fa fa-pencil"></i> Employees</li>
        </ol>
    </div>

    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="main-content-block">

                    @if (Session::has('message'))
                        <div class="alert alert-info">{!! Session::get('message') !!}</div>
                    @endif

                    @can('employees-add')
                        <div class="btnbar btnbar-right"><a class="btn btn-small btn-primary" href="{!! URL::to('/admin/employees/create') !!}">Create new</a></div>
                    @endcan

                    <h2>Overview</h2>

                    <table id="datatable" class="table table-hover table-condensed" style="width:100%">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Title</th>
                            <th style="width:200px;">Category</th>
                            <th>Country</th>
                            <th></th>
                        </tr>
                        </thead>
                    </table>

                    <script type="text/javascript">
                        $(document).ready(function () {
                            oTable = $('#datatable').DataTable({
                                "pageLength": 50,
                                "processing": true,
                                "serverSide": true,
                                "ajax": "{{ route('admin.employees.api.table') }}",
                                "columns": [
                                    {data: 'id', name: 'ID'},
                                    {data: 'title', name: 'employees_language.title'},
                                    {data: 'category', name: 'employees_categories_language.title'},
                                    {data: 'country', name: 'country', searchable: false},
                                    {data: 'edit', name: 'edit', orderable: false, searchable: false}
                                ]
                            });
                        });
                    </script>


                    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.css">

                    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
                    <script type="text/javascript" language="javascript"
                            src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js"></script>

                </div>
            </div>
        </div>
    </div>

@stop